#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'snowplow'
version: '0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  snowplow:
    base:
      materialized: ephemeral  
      optional:
        enabled: false
    page_views:
      optional:
        enabled: false

    vars:
      'snowplow:use_fivetran_interface': false
      #'snowplow:events': TABLE OR {{ REF() }}
      #'snowplow:context:web_page': TABLE OR {{ REF() }}
      #'snowplow:context:performance_timing': TABLE OR {{ REF() }} or FALSE
      #'snowplow:context:useragent': TABLE OR {{ REF() }} or FALSE
      'snowplow:timezone': 'America/New_York'
      'snowplow:page_ping_frequency': 30
      'snowplow:app_ids': []
      'snowplow:bot_useragents':
        - bot
        - crawl
        - slurp
        - spider
        - archiv
        - spinn
        - sniff
        - seo
        - audit
        - survey
        - pingdom
        - worm
        - capture
        - (browser|screen)shots
        - analyz
        - index
        - thumb
        - check
        - facebook
        - PingdomBot
        - PhantomJS
        - YandexBot
        - Twitterbot
        - a_archiver
        - facebookexternalhit
        - Bingbot
        - BingPreview
        - Googlebot
        - Baiduspider
        - 360(Spider|User-agent)
        - semalt
