
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            mkdir -p /opt/dbt/
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > /opt/dbt/gcloud-service-key.json

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install dbt
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - BigQuery"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/opt/dbt/gcloud-service-key.json"

          command: |
            . venv/bin/activate
            cd integration_tests
            dbt deps --target bigquery
            dbt seed --target bigquery --full-refresh
            dbt run --target bigquery --full-refresh
            dbt run --target bigquery
            dbt test --target bigquery

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
