
name: 'snowplow_integration_tests'
version: '1.0'

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false

models:
  vars:
    'snowplow:timezone': 'America/New_York'

  snowplow:
    vars:
      'snowplow:events': '{{ ref("event") }}'
      'snowplow:context:web_page': '{{ ref("web_page") }}'
      'snowplow:context:performance_timing': FALSE
      'snowplow:context:useragent': FALSE

seeds:
  snowplow_integration_tests:
    pre-hook:
      - |
        {% if target.name != 'bigquery' %}
          create schema if not exists {{ this.schema }}
        {% else %}
          select 1 as id -- pass
        {% endif %}

    snowplow:
      event:
        column_types:
          collector_tstamp: timestamp
